### ISSUE TITLE
Complex Sequence Input

### ISSUE THREAD

**Issue by rkruegs123** [sokrypton/ColabFold#164]
## Expected Behavior

Suppose we want to predict a tetramer with two subunits, A and B, and two copies of each subunit. I understand that the input on the notebooks would be something like `<sequence of A>:<sequence of B>` and `2:2`. This is very intuitive to me if the true structure of the complex looks something like `A-A-B-B`. However, does providing input in this form also handle other cases? E.g. `A-B-A-B`. More generally, **how constrained is the ordering of subunits for complex prediction**? Given two subunits with copy numbers X and Y, does `X:Y` only allow for structure predictions in which `X` copies of the first subunit are followed by `Y` copies of the second subunit, or does it also allow for intermixing of the subunits?

## Current Behavior

Unclear

## Context

I ask because if complex prediction is implemented using the glycine linkers, it is unclear to me how the linkers would be implemented to achieve the more general case.

**Comment by sokrypton** [comment]
Some technical details as to why the prediction may change if you change the order:
AlphaFold randomly masks 15% of the MSA (and within that 15%, It randomly mutates some of the amino acids). So if the order of the input chains is different, that changes what positions are masked within the MSA and so that may result in different predictions.

So in other words, changing the order of the inputs can potentially give you a better or worse prediction (but iterating through random seeds will accomplish the same thing).

To disable this behavior:
cfg.data.eval.masked_msa_replace_fraction = 0

**Comment by rkruegs123** [comment]
Thank you so much!
