### ISSUE TITLE
Multimer IPTM score

### ISSUE THREAD

**Issue by xvazquezc** [sokrypton/ColabFold#194]
Hi there,

quick question, when modelling complexes, are the IPTM scores stored somewhere in the standard output files? or are they just used internally for the scoring/ranking?

Thanks

**Comment by martin-steinegger** [comment]
We do not store the information atm.

**Comment by gtauriello** [comment]
@martin-steinegger if I may add, I think it would be good to have ipTM in the scores json. Especially if the ranking is done with the multimer-ranking. Otherwise, you end up with a ranking where the relevant ranking-score is missing from the output, which makes it more difficult to interpret the results. Also it seems like a trivial addition to the code for a future ColabFold-version since you already get iptmscore anyway...

**Comment by martin-steinegger** [comment]
The iptm can be computed from the ptm matrix that we do provide in our json file. 
So you can compute the iptm. But I agree that it would be good to include the value itself.

**Comment by gtauriello** [comment]
I assume you mean the PAE matrix (instead of "ptm matrix")?

To the best of my knowledge, PAE, pTM and ipTM are all derived from the same NN output (which I think is available in the pickle-files produced by AF), but there is no formula that would compute ipTM (or pTM) using the PAE values as input. At least that was my interpretation of reading section 1.9.7 in the AlphaFold-paper-supplement. I think you would need the prob. distr. of PAE to compute pTM and ipTM. Or am I missing something?

**Comment by gtauriello** [comment]
As I was looking at ipTM values in old and new ColabFold outputs I remembered that there was this issue here. Since quite a few ColabFold versions (not sure when exactly this changed), there is ipTM in the scores JSON so this issue can be closed I think.
