### ISSUE TITLE
Running Locally with Custom Templates and MSA 

### ISSUE THREAD

**Issue by RaymondRuff** [sokrypton/ColabFold#236]
## Expected Behavior
I am running colabfold locally on an HPC that is currently not making calls to get MSAs or templates from the PDB70 (will be set up to have databases stored locally soon). As a test, I am providing a precomputed MSA as the input and have a folder with the mmCIF of the actual crystal solution to provide as a template (I am not interested in the structure, just a troubleshooting strategy). For some reason, when I specify --templates --custom-template-path templates/ it is not using the template. I have also placed the mmCIF in a bar_env folder and removed the --custom-template-path arg but get the same results.

I expected a line stating:
Sequence 0 found templates: ['6cdx_A', '6cdx_B']
This line is present when I submit the sequence into Google Colab and upload the template file I am using as a custom template so I know it is correctly formatted.

## Current Behavior
Given command:
$ colabfold_batch input/6CDX_msa.a3m output/ --templates --custom-template-path templates/ --num-models 1

The provided template is ignored although it is being processed in some way as four new files are produced: pdb70_a3m.ffdata, pdb70_a3m.ffindex, pdb70_cs219.ffdata, pdb70_cs219.ffindex

## Steps to Reproduce (for bugs)
Install colabfold locally as instructed. Generate MSA by submitting sequence to google colab and downloading result. Create a folder 'templates' and upload the PDBx/mmCIF file downloaded from https://www.rcsb.org/structure/6CDX. Run command as above. Keep in mid HPC is not connected to internet.

## ColabFold Output (for bugs)
2022-06-01 08:11:20,160 Running colabfold 1.3.0 (7227d4c9e0a8f08ac96e8b56add675baf3c69cdb)
2022-06-01 08:11:53,522 Found 7 citations for tools or databases
2022-06-01 08:11:57,674 Query 1/1: 6CDX_msa (length 37)
2022-06-01 08:11:57,680 Running model_3
2022-06-01 08:13:42,099 model_3 took 101.6s (3 recycles) with pLDDT 69.8
2022-06-01 08:13:45,249 reranking models by plddt
2022-06-01 08:13:45,662 Done

## Context
Some explanation for what is needed beyond putting the mmCIF file in a directory to ensure custom templates are being found and used.

## Your Environment
Server Specs: 
CPU: Single core Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
RAM: 2GB
GPU: 1 Tesla P100-PCIE-16GB

**Comment by RaymondRuff** [comment]
This worked! What I did was copy the contents of the _env folder generated by google colabfold to the bar_env folder on the HPC which contain the files you stated. The a3m for the query must also be in the bar_env folder. Does the folder need to be named "bar_env" or does the program look for a folder with the _env suffix?

**Comment by tubiana** [comment]
Hello :) 
I would like to come back on this, does this still work with current version of colabfold ? 
I followed the procedure but it doesn't work for me. Therefore I have to use the MSA generated by the MMSEQS server which is way bigger...

Thank you :)

**Comment by RaymondRuff** [comment]
It does still work for me, however there are many places at which things can go awry. Are you sure you need custom templates and there is no way of setting up communication with the MMSeqs2 server to handle this? Although I got this workaround to work with help, I have since been able to get the HPC to connect to the MSA server and life is much better for use of custom templates. 

With that said, here is a bit of a more exhaustive outline. 

1. Submit sequence to google colab
2. Zip and download the output folder
3. unzip and copy the folder within the output called <yourJobName>_env to your HPC inside of the output folder you specify when you run colabfold_batch. As a note, some times the _env folder needs to be generated by the HPC before it will recognize it, not sure why. If the following steps are followed and it does not use the templates, look for a new _env folder in the output directory generated by the failed attempt. Remove all contents from that folder and upload everything from the google colab generated _env folder there.
4. Also place into the _env folder the google colab generated Templates_101 folder and the .a3m MSA
5. Create fasta file of sequence you want to fold, be sure the header of the fasta matches the name of the _env folder in your output directory.
6. Upload desired custom templates to a folder, be sure they are properly formatted mmCIFs
7. run colabfold_batch and cross your fingers

Like stated above I am hopeful they flesh this out further because the use case is not uncommon. Hope that helps!

**Comment by tubiana** [comment]
Thank you for your answer =D 

I used colabfold locally through a singularity container, but I managed to generate the "_env" folder by submiting the fasta file directly to colabfold_batch :) 
I followed your procedure and it works thank you =D

Maybe I should open a ticket to check if it is possible to update colabfold to take an MSA directly, because it's not fair for other users to used the MMSEQS server when we actually don't need it.

**Comment by martin-steinegger** [comment]
Colabfold can take MSAs directly. Here is an example command to search and predict structures from the generated MSAs.

```
# This needs CPU
colabfold_search input_sequences.fasta /path/to/db_folder msas
# This needs a GPU
colabfold_batch msas predictions
```

**Comment by tubiana** [comment]
Hi :) 

Yes this is very handy, and this is how we use it (here's my submission script for exemple, with a colabfold_search followed by a colabfold_batch https://github.com/tubiana/colabfold_singularity/blob/main/run_pred.sh ) :-)

The problem was than when I give the msa folder to colabfold_batch (something like `colabfold_batch --template --custom-template-path templates msas predictions` the templates are ignored (I have an error message like `0 templates found`)
So the workarround, as @RaymondRuff said, is to :
1. generate the msa with colabfold_search
2. Starting a run with `colabfold_batch` front the single sequence fasta only in order to have the folder `XXX_env` in the output folder (`colabfold_batch --template --custom-template-path templates seq.fasta predictions`)
3. Killing the jobs when the models starts
4. Copy the custom msa in `output/XXX_env` and in `output`
5. Restarting `colabfold_batch` from the single sequence again. The MSAS calculation will be then skipped, the custom msa will be used with the templates

So now it works =D But it means that we still need to use the msas server, even if we don't need it... and I was a bit concerned regarding the fair use of the server :)
