### ISSUE TITLE
ColabFold v1.5.2: AlphaFold2 using MMseqs2 Error While Installing Dependencies

### ISSUE THREAD

**Issue by osmanmerdan** [sokrypton/ColabFold#437]
## Expected Behavior
To install dependencies
## Current Behavior
Prints an error message and stops working during the install dependencies step. 
## Steps to Reproduce (for bugs)
I was using ColabFold v1.5.2: AlphaFold2 using MMseqs2 AlphaFold2.ipynb Notebook. 
I have Colab Pro. My runtime settings:
Hardware accelerator = GPU, GPU class = Premium, Runtime shape = High memory, RAM = 86GB, Disk = 166GB, There was no data about GPU RAM. 
- Query Sequence:  A viral protein (https://www.ncbi.nlm.nih.gov/protein/52139269) ( length 707 amino acids )
- num_relax = 1
- template_mode = pdb70
- All other settings were left as they are. 
## ColabFold Output (for bugs)
To keep this thread clean, I have attached the error message as a text file.
[error.txt](https://github.com/sokrypton/ColabFold/files/11353516/error.txt) 
## Context
I tried 3 times and got the same error every time. Before each trial, I deleted the runtime and restarted the colab session. 
Important Note: I did not encounter any issue with "num_relax = 0". I think the problem is somewhat related to amber. But I am not a CS person. 

Thanks in advance.

**Comment by jfbazan** [comment]
I think I'm seeing the same bug! As in the above case, I'm running ColabFold1.5.2's AF2.ipynb notebook, routine settings, worked well 2 days ago with a series of protein multimer cases. The crash only happens if I toggle on the 'relax' routine to be run at the end of the prediction (so I typically set num_relax=1 to catch the top-ranked model), and then after hitting the 'run all' command, the notebook just spins its wheels and reveals nothing for a good 15 min in the Install Dependencies section, before spitting out the following, very long error message. The top of the error return follows below, followed by the end (it's a very long error msg...;). The comments at the very end point towards problems with AMBER, as intuited in the first comment by Osman. If I run the same prediction run but turn off the 'relax' (set num_relax=0), it will run normally and give predictions as usual, but lacking the AMBER relax, so that pinpoints this new error!  I should note that the DeepMind AF2 colab runs just fine with its version of relax, so this just affects the main ColabFold notebook.  Thx in advance for pursuing this problem! 

installing colabfold...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.5/221.5 MB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 111.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 44.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 48.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.1/352.1 kB 38.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 30.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 10.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 99.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.5/147.5 kB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 109.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 56.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 MB 5.8 MB/s eta 0:00:00
installing conda...
installing amber...
                                                                                       
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (python):

  - cryptography==38.0.4 -> cffi[version='>=1.12'] -> python[version='3.10.*|3.11.*|3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.8.16|3.9.16|3.9.10|>=3.6,<3.7.0a0|3.7.9|3.6.9|3.6.9|3.6.9|>=2.7,<2.8.0a0|3.6.9|3.8.*|3.9.*',build='0_73_pypy|2_73_pypy|3_73_pypy|5_73_pypy|5_73_pypy|1_73_pypy|0_73_pypy|0_73_pypy|4_73_pypy|1_73_pypy']
  - cryptography==38.0.4 -> python[version='>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0']
  - openmm=7.5.1 -> numpy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.5,<3.6.0a0|3.4.*|3.7.*|3.9.*|3.8.*']
  - openmm=7.5.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']
  - pdbfixer -> numpy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*|>=3.7|>=3.8']
  - pdbfixer -> python[version='>=3.6']
  - pdbfixer -> setuptools
  - python=3.10 -> pip -> setuptools
  - python=3.10 -> pip -> wheel

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _openmp_mutex conflicts for:
bzip2 -> libgcc-ng[version='>=9.3.0'] -> _openmp_mutex[version='>=4.5']
ruamel.yaml -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
zstandard -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
readline -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
sqlite -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
libgcc-ng -> _openmp_mutex[version='>=4.5']
openssl -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
cryptography==38.0.4 -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
zlib -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
libuuid -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
cffi -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
conda-package-handling -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
pycosat -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
libffi -> libgcc-ng[version='>=9.4.0'] -> _openmp_mutex[version='>=4.5']
brotlipy -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
openmm=7.5.1 -> libgcc-ng[version='>=7.5.0'] -> _openmp_mutex[version='>=4.5']
ruamel.yaml.clib -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
tk -> libgcc-ng[version='>=9.4.0'] -> _openmp_mutex[version='>=4.5']
ncurses -> libgcc-ng[version='>=10.3.0'] -> _openmp_mutex[version='>=4.5']
xz -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']
_openmp_mutex
python=3.10 -> libgcc-ng[version='>=12'] -> _openmp_mutex[version='>=4.5']

Then it goes package by package detailing conflicts, and finishing up with this:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.11.0 which is incompatible.
tensorflow 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.19.6 which is incompatible.
tensorflow 2.12.0 requires tensorboard<2.13,>=2.12, but you have tensorboard 2.11.2 which is incompatible.
tensorflow 2.12.0 requires tensorflow-estimator<2.13,>=2.12.0, but you have tensorflow-estimator 2.11.0 which is incompatible.
orbax-checkpoint 0.2.1 requires jax>=0.4.8, but you have jax 0.3.25 which is incompatible.
flax 0.6.9 requires jax>=0.4.2, but you have jax 0.3.25 which is incompatible.
chex 0.1.7 requires jax>=0.4.6, but you have jax 0.3.25 which is incompatible.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-2-6df292f23d6c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '-s $use_amber $use_templates $python_version', '\nset -e\n\nUSE_AMBER=$1\nUSE_TEMPLATES=$2\nPYTHON_VERSION=$3\n\nif [ ! -f COLABFOLD_READY ]; then\n  echo "installing colabfold..."\n  # install dependencies\n  # We have to use "--no-warn-conflicts" because colab already has a lot preinstalled with requirements different to ours\n  pip install -q --no-warn-conflicts "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold" "tensorflow-cpu==2.11.0"\n  pip uninstall -yq jax jaxlib\n  pip install -q "jax[cuda]==0.3.25" -f [https://storage.googleapis.com/jax-releases/jax_cuda_releases.html\n\n\n](https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/n/n/n)  # for debugging\n  ln -s /usr/local/lib/python3.*/dist-packages/colabfold colabfold\n  ln -s /usr/local/lib/python3.*/dist-packages/alphafold alphafold\n  touch COLABFOLD_READY\nfi\n\n# setup conda\nif [ ${USE_AMBER} == "True" ] || [ ${USE_TEMPLATES} == "True" ]; then\n  if [ ! -f CONDA_READY ]; then\n    echo "installing conda..."\n    wget -qnc [https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh\n](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh/n)    bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local 2>&1 1>/dev/null\n    rm Miniconda3-latest-Linux-x86_64.sh\n    conda config --set auto_update_conda false\n    touch CONDA_READY\n  fi\nfi\n# setup template search\nif [ ${USE_TEMPLATES} == "True" ] && [ ! -f HH_READY ]; then\n ...

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'\nset -e\n\nUSE_AMBER=$1\nUSE_TEMPLATES=$2\nPYTHON_VERSION=$3\n\nif [ ! -f COLABFOLD_READY ]; then\n  echo "installing colabfold..."\n  # install dependencies\n  # We have to use "--no-warn-conflicts" because colab already has a lot preinstalled with requirements different to ours\n  pip install -q --no-warn-conflicts "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold" "tensorflow-cpu==2.11.0"\n  pip uninstall -yq jax jaxlib\n  pip install -q "jax[cuda]==0.3.25" -f [https://storage.googleapis.com/jax-releases/jax_cuda_releases.html\n\n\n](https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/n/n/n)  # for debugging\n  ln -s /usr/local/lib/python3.*/dist-packages/colabfold colabfold\n  ln -s /usr/local/lib/python3.*/dist-packages/alphafold alphafold\n  touch COLABFOLD_READY\nfi\n\n# setup conda\nif [ ${USE_AMBER} == "True" ] || [ ${USE_TEMPLATES} == "True" ]; then\n  if [ ! -f CONDA_READY ]; then\n    echo "installing conda..."\n    wget -qnc [https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh\n](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh/n)    bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local 2>&1 1>/dev/null\n    rm Miniconda3-latest-Linux-x86_64.sh\n    conda config --set auto_update_conda false\n    touch CONDA_READY\n  fi\nfi\n# setup template search\nif [ ${USE_TEMPLATES} == "True" ] && [ ! -f HH_READY ]; then\n  echo "installing hhsuite..."\n  conda install -y -q -c conda-forge -c bioconda kalign2=2.04 hhsuite=3.3.0 python="${PYTHON_VERSION}" 2>&1 1>/dev/null\n  touch HH_READY\nfi\n# s...

**Comment by martin-steinegger** [comment]
Google updated the Colab environment today and the new python version is incompatible with the Amber version we use. We are working on it.

**Comment by milot-mirdita** [comment]
We disabled `num_relax` for now. I'll try to implement a real fix tomorrow.

**Comment by osmanmerdan** [comment]
Thanks for the quick response. Everything works smoothly.
