### ISSUE TITLE
"single representation" shape is (L,256) instead of (L,384)

### ISSUE THREAD

**Issue by htalibart** [sokrypton/ColabFold#472]
Hello,

When running the AlphaFold2_mmseqs2 notebook with the example provided and checking the "save_all" box, the output folder contains several .npy files with "single_repr" and "pair_repr" names. I was expecting the "single_repr" files to contain the "single representations" extracted in line 12 of algorithm 6 "Evoformer stack" in AlphaFold2 Supplementary Material, whose dimensions are (L,384), but the files contain arrays of dimensions (L,256).

Is it possible that these "single_repr" files don't actually contain the "single representations" but rather the first rows of the "msa representations"?

Thank you!

**Comment by sokrypton** [comment]
This was intentional, we were trying to reduce memory leaks and return the bare minimum.

The msa_activation is (N,L,256), in colabfold we return msa_activation[0] as our single representation vector.

As seen in screenshot below. There is a linear layer that converts the 256 features to 384.
<img width="672" alt="image-46" src="https://github.com/sokrypton/ColabFold/assets/4187522/b3c9c5a7-d12c-4462-ab97-7b80c3e93182">

 If you need the (L,384), it should be a simple linear transformation using the weights from the single_activation layer. 
<img width="955" alt="image-42" src="https://github.com/sokrypton/ColabFold/assets/4187522/3b35a07f-7d85-44b3-a257-115ce9679ced">

Though if anything the (L,256) representation might be better, as you might be losing some information by doing the extra transformation at the end.

**Comment by sokrypton** [comment]
Still trying to decide if I should keep encouraging people to use the 256 representations... Or just force the irreversible conversation to the 384 representation?

**Comment by htalibart** [comment]
Many thanks for your answer!

Personally I'm ok with the 256 representations since they can be easily transformed to 384 representations if needed, but maybe the variable names could be changed to make it clearer...? (I did spend a lot of time trying to figure out what was wrong, at first I thought maybe I was using the wrong pre-trained model or something)

I'm curious as to why you think that information is lost with this extra transformation, if this is the case then in your opinion why is the Structure module using the transformed representation and not the raw one?

**Comment by sokrypton** [comment]
Just theoretically, if you do a matrix multiplication you might be masking some non-informative features for downstream tasks.

The (L,256) is used for multiple down stream tasks (MSA regeneration for the Masked-language-modeling task) then after the (L,384) transformation as input to structure module, then later after modification by structure module for pLDDT prediction.

Finally the (L,256) is recycled and used as input to alphafold at each recycle.

There is an incentive to preserve as much info in the 256 as possible. While the 384 is only used for one side task.

**Comment by htalibart** [comment]
Oh ok I understand.
Thank you :)

**Comment by stianale** [comment]
> If you need the (L,384), it is a simple linear transformation using the weights from the single_activation layer: <img alt="image-42" width="955" src="https://user-images.githubusercontent.com/4187522/251312603-3b35a07f-7d85-44b3-a257-115ce9679ced.png">

It is not clear to me where to put this code that you suggested: 

W = af_model._model_params[0]['alphafold/alphafold_iteration/evoformer/single_activations']

```
af_model.aux["debug"]["outputs"]["representations"].keys()

plt.scatter(af_model.aux["debug"]["outputs"]["representations"]["single"],
            af_model.aux["debug"]["outputs"]["representations"]["msa_first_row"] @ W ["weights"] + W ["bias"],
            s=1)
```

I simply want to download the L x 384 numpy array together with the rest of the output. I am using AlphaFold2.ipynb
