### ISSUE TITLE
is_training explained

### ISSUE THREAD

**Issue by xvazquezc** [sokrypton/ColabFold#68]
Hi there, 
I'm trying to improve the model of a protein for which the default parameters don't give great results. I've seen the `is_training` option and aside of provide a wider search space using heuristics and multiple seeds when combined with `num_samples` I don't see a good explanation of how does it. Basically because you can still use `num_samples` without `is_training`, with a way longer processing time though.
Any details would be appreciated.
Thanks

**Comment by sokrypton** [comment]
There are a couple of stochastic parts in AlphaFold that are controlled by random seed:
1) MSA clustering and masking.
2) Dropout within AlphaFold. (if "is_training" is enabled)

num_samples defines the number of random seeds to try that feeds into both (1) and (2). if is_training is disabled only (1) is perturbed due to different seeds.

disabling is_training shouldn't make things much slower.... I'll investigate.

**Comment by xvazquezc** [comment]
Oh, my bad, the run I had without `is_training` had a much larger recycle number, the slow down is most likely due to it.

This protein also has very low coverage based on the MSA (most of it <30), so I've been doing some runs with increased recycles. Maybe is a dumb question but, would you increase the number of recycles together with `is_training` or there is a way to reuse a seed/model from a prior search with `is_training` and do more recycles in that single seed/model combination?
