### ISSUE TITLE
Doubts on local MMseqs search

### ISSUE THREAD

**Issue by SSchott** [sokrypton/ColabFold#91]
Hi,
So we have been trying to implement the local mmseqs/search, and it is at least for me unclear what is the best setup/config for having this running on a dedicated machine. 

Right now we tried following the database generation instructions of the webpage and as specified in setup_databases.sh. There the first question would be, if any parameter to setup the split level is required. In the guide it is mentioned that not creating an index file could help, but is also not 100% clear how to run the scripts without such files.
Then, when running things as specified in colabfold_search.sh, the executables seem to be bound to 100% cpu usage, even when setting OMP_NUM_THREADS to a higher number. Are we missing some parameter here? We also tested the MPI implementation, but it didn't seem to help, and since we are running things in a single node, the OMP implementation seems to make more sense.

We also realized that there was a lot of time wasted in loading the index into the memory, and followed the suggestion of using vmtouch to precache it and speed things up. The speed of the search improved noticeably, but still bound to 100%. In this regard, the recommendation would be to load both uniref and colabfold DBs into the cache? Is there anyway in which we can split this step so we don't load 550+GBs into memory?

Thanks!

**Comment by martin-steinegger** [comment]
You have two ways how to use MMseqs2: 
(1) batch search: Instead of searching one query at a time you can search multiple at once. For this you do not need any index. This kind of search would probably require a machine with 128 to 256GB for the colabfolddb. You can just skip the `createindex` step.
(2) online search: If you'd like to provide a dedicated server to perform fast single query searches then you need a high memory machine > 700GB RAM. Here the trick is to compute a single index file with `createindex` and `vmtouch` it into memory. If you perform now searches you can add the `--db-load-mode 3` flag to MMseqs2, it will assume that the index is already cached in memory.

**Comment by SSchott** [comment]
Hi Martin,
Thanks for the answer, I'll keep it in mind. While we setup a dedicated machine for this, we have been using this modded script by @milot-mirdita https://gist.github.com/milot-mirdita/67509c248746c4c774128fc84ab91b6f
Maybe this should replace the colabfold_search.sh script distributed in the page?
